#!/bin/sh -eux
DIR=~/dotfiles
mkdir -p ~/.config
mkdir -p ~/.vim
ln -sf "$DIR/.bashrc" ~/.bashrc
ln -sf "$DIR/.config/bash_completion" ~/.config
ln -sf "$DIR/.config/git-completion.bash" ~/.config
ln -sf "$DIR/.config/git-prompt.sh" ~/.config
ln -sf "$DIR/.ctags" ~/.ctags
ln -sf "$DIR/.gitconfig" ~/.gitconfig
ln -sf "$DIR/.inputrc" ~/.inputrc
ln -sf "$DIR/.screenrc" ~/.screenrc
ln -sf "$DIR/.tmux.conf" ~/.tmux.conf
ln -sf "$DIR/.vim/pack" ~/.vim
ln -sf "$DIR/.vimrc" ~/.vimrc
exec $SHELL -l
